## Start the system with "docker-compose up -d"
## Shutdown it with "docker-compose down"
## To clean your docker install: "docker system prune"
## To purge your docker install: "docker system prune -a"

version: '3'

services:

  hotel-planner:
    container_name: tcs-hotel
    image: petitroll/tcs-rest-hotel
    ports:
      - "9090:8080"

  flight-planner:
    container_name: tcs-flight
    image: petitroll/tcs-doc
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9080:8080"

  database:                       # MongoDB database, on port 27017
    container_name: tcs-database
    image: mongo:3.0
    volumes:
      - "./mongo_data:/data/db"
    ports:
      - "27017:27017"
