## Start the system with "docker-compose up -d"
## Shutdown it with "docker-compose down"
## To clean your docker install: "docker system prune"
## To purge your docker install: "docker system prune -a"

version: '3'

services:

  hotel-planner:
    container_name: hotel-planner
    image: petitroll/hotel-planner
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9090:8080"

  flight-planner:
    container_name: tcs-flight
    image: petitroll/tcs-doc
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9080:8080"

  travel-manager:
    container_name: travel-manager
    image: petitroll/travel-manager
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9070:8080"

  car-planner:
    container_name: car-planner
    image: petitroll/car-planner
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9060:8080"

  database:
    container_name: tcs-database
    image: mongo:3.0
    volumes:
      - "./mongo_data:/data/db"
    ports:
      - "27017:27017"

#  cadvisor:                       # Container monitoring, on port 8090
#    container_name: tcs-monitoring
#    image: petitroll/cadvisor     # filesystem error in the official image ... fixed in 'monitoring'
#    ports:
#      - "8090:8080"
#    volumes:
#      - "/:/rootfs:ro"
#      - "/var/run:/var/run:rw"
#      - "/sys:/sys:ro"
#      - "/var/lib/docker/:/var/lib/docker:ro"
