version: '3'

services:

#other groups
  other-flights:
    container_name: other-flights
    image: earendil06/other-flights
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9180:8080"

  other-hotels:
    container_name: other-hotels
    image: earendil06/other-hotels
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9380:8080"

  other-cars:
    container_name: travel-cars
    image: earendil06/travel-cars
    ports:
      - "9280:8080"

#us
  hotel-planner:
    container_name: hotel-planner
    image: hotel-planner
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9090:8080"

  flight-planner:
    container_name: tcs-flight
    image: tcs-doc
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9080:8080"


#  travel-manager:
#    container_name: travel-manager
#    image: travel-manager
#    environment:
#      - db_host=tcs-database
#      - db_port=27017
#    depends_on:
#      - database
#    ports:
#      - "9070:8080"

  car-planner:
    container_name: car-planner
    image: car-planner
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9060:8080"
#
#  integration-bus:  # To attach to this container at runtime: docker exec -it tcs-bus sh
#    container_name: integration
#    image: integration
#    volumes:
#      - "./camel_input:/servicemix/camel/input"
#      - "./camel_output:/servicemix/camel/output"
#    ports:
#      - "8181:8181"
#      - "8101:8101"
#      - "1099:1099"
#      - "61616:61616"
#      - "44444:44444"
#    depends_on:
#      - hotel-planner
#      - car-planner

  database:
    container_name: tcs-database
    image: mongo:3.0
    volumes:
      - "./mongo_data:/data/db"
    ports:
      - "27017:27017"



#  cadvisor:                       # Container monitoring, on port 8090
#    container_name: tcs-monitoring
#    image: cadvisor     # filesystem error in the official image ... fixed in 'monitoring'
#    ports:
#      - "8090:8080"
#    volumes:
#      - "/:/rootfs:ro"
#      - "/var/run:/var/run:rw"
#      - "/sys:/sys:ro"
#      - "/var/lib/docker/:/var/lib/docker:ro"
