version: '3'

services:

#other groups
  other-flights:
    container_name: other-flights
    image: earendil06/other-flights
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9180:8080"

  other-hotels:
    container_name: other-hotels
    image: earendil06/other-hotels
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9380:8080"

  other-cars:
    container_name: other-cars
    image: earendil06/other-cars
    ports:
      - "9060:9060"

#us
  our-hotels:
    container_name: our-hotels
    image: earendil06/our-hotels
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9090:8080"

  our-flights:
    container_name: our-flights
    image: earendil06/our-flights
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9080:8080"

  our-cars:
    container_name: our-cars
    image: earendil06/our-cars
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9160:8080"

  travel-manager:
    container_name: travel-manager
    image: anthonyfusco/travel-manager
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9070:8080"

  travel-manager2:
    container_name: travel-manager2
    image: anthonyfusco/travel-manager
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9071:8080"

  integration-bus:  # To attach to this container at runtime: docker exec -it integration sh
    container_name: integration
    image: integration
    volumes:
      - "./camel_input:/servicemix/camel/input"
      - "./camel_mail:/servicemix/camel/mail"
      - "./camel_output:/servicemix/camel/output"
      - "./camel_archive:/servicemix/camel/archive"
    ports:
      - "8181:8181"
      - "8101:8101"
      - "1099:1099"
      - "61616:61616"
      - "44444:44444"

  database:
    container_name: tcs-database
    image: mongo:3.0
    volumes:
      - "./mongo_data:/data/db"
    ports:
      - "27017:27017"


#  cadvisor:                       # Container monitoring, on port 8090
#    container_name: tcs-monitoring
#    image: cadvisor     # filesystem error in the official image ... fixed in 'monitoring'
#    ports:
#      - "8090:8080"
#    volumes:
#      - "/:/rootfs:ro"
#      - "/var/run:/var/run:rw"
#      - "/sys:/sys:ro"
#      - "/var/lib/docker/:/var/lib/docker:ro"
