package hotelplanner.planner.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-10-08T17:36:11.618+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "HotelPlannerService", 
                  wsdlLocation = "file:/home/afusco/IdeaProjects/lab1-travel-agency-fusco-suignard-balde-pastor/tests/acceptation/src/main/resources/HotelPlannerService.wsdl",
                  targetNamespace = "http://service.planner/") 
public class HotelPlannerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.planner/", "HotelPlannerService");
    public final static QName HotelPlannerPort = new QName("http://service.planner/", "HotelPlannerPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/afusco/IdeaProjects/lab1-travel-agency-fusco-suignard-balde-pastor/tests/acceptation/src/main/resources/HotelPlannerService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HotelPlannerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/afusco/IdeaProjects/lab1-travel-agency-fusco-suignard-balde-pastor/tests/acceptation/src/main/resources/HotelPlannerService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HotelPlannerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HotelPlannerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelPlannerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HotelPlannerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HotelPlannerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HotelPlannerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HotelPlanner
     */
    @WebEndpoint(name = "HotelPlannerPort")
    public HotelPlanner getHotelPlannerPort() {
        return super.getPort(HotelPlannerPort, HotelPlanner.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelPlanner
     */
    @WebEndpoint(name = "HotelPlannerPort")
    public HotelPlanner getHotelPlannerPort(WebServiceFeature... features) {
        return super.getPort(HotelPlannerPort, HotelPlanner.class, features);
    }

}
