package carplanner.planner.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-10-08T17:11:36.842+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://service.planner/", name = "CarPlanner")
@XmlSeeAlso({ObjectFactory.class})
public interface CarPlanner {

    @WebMethod
    @RequestWrapper(localName = "getAllCars", targetNamespace = "http://service.planner/", className = "planner.service.GetAllCars")
    @ResponseWrapper(localName = "getAllCarsResponse", targetNamespace = "http://service.planner/", className = "planner.service.GetAllCarsResponse")
    @WebResult(name = "all_car_result", targetNamespace = "")
    public java.lang.String getAllCars();

    @WebMethod
    @RequestWrapper(localName = "getCarByPlace", targetNamespace = "http://service.planner/", className = "planner.service.GetCarByPlace")
    @ResponseWrapper(localName = "getCarByPlaceResponse", targetNamespace = "http://service.planner/", className = "planner.service.GetCarByPlaceResponse")
    @WebResult(name = "car_planner_result", targetNamespace = "")
    public java.lang.String getCarByPlace(
        @WebParam(name = "place", targetNamespace = "")
        java.lang.String place,
        @WebParam(name = "duration", targetNamespace = "")
        int duration
    );
}
